[package]
name = "blockchain-rev"
version = "1.0.0"
authors = []

[addresses]
blockchain_rev_addr = "693ead2bcaddbc1643efbf1328dec691ba57ca814784d63aa4a82678ef4e441a"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
